server:
  port: 8081 # API будет доступно на порту 8081

spring:
  application:
    name: search-api
  
  # Настройки подключения к Elasticsearch
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    socket-timeout: 10s

  # Подключение к БД PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/crawler
    username: crawler_user
    password: crawler_password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO
    io.github.ymatojava: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: TRACE # Для отладки запросов к ES
